/* quiz studio — subject / chapter metadata, references, image-prompt scenes */
var SUBJ={
 general:{ko:'일반',en:'General',site:'general',hb:'FAA-H-8083-30B · AMT Handbook — General',acs:'FAA-S-ACS-1 · Aviation Mechanic ACS (General)',
  ch:{1:['항공 입문','Introduction to Aviation','early aviation history, a vintage biplane beside a modern jet in one hangar','오래된 복엽기와 현대 제트기가 함께 선 격납고'],
   2:['항공 수학','Aviation Mathematics','engineering calculations, a technician measuring with a precision scale over blueprints','도면 위에서 정밀 스케일로 치수를 계산하는 정비사'],
   3:['기초 물리','Basic Physics','airflow lines and pressure gradients flowing around a wing section','날개 단면 주위로 흐르는 공기 흐름과 압력 분포'],
   4:['기초 전기','Basic Electricity','glowing circuit paths, a multimeter probing an aircraft wiring bundle','항공기 배선 다발을 멀티미터로 측정하는 장면'],
   5:['항공기 도면','Aircraft Drawings','technical blueprint of an aircraft on a drafting table under a desk lamp','책상 조명 아래 펼쳐진 항공기 기술 도면'],
   6:['무게와 평형','Weight and Balance','aircraft resting on three platform scales in a hangar, CG concept','격납고에서 3개의 저울 위에 올라간 항공기'],
   7:['재료와 공정','Materials and Processes','close-up of aerospace fasteners, rivets and alloy samples on a workbench','작업대 위 항공용 볼트·리벳·합금 시편 클로즈업'],
   8:['세척과 부식방지','Cleaning and Corrosion Control','corroded aluminum panel being inspected with a flashlight','손전등으로 부식된 알루미늄 패널을 검사하는 장면'],
   9:['유체 라인과 피팅','Fluid Lines and Fittings','braided hydraulic hoses and flared tube fittings in macro detail','편조 유압 호스와 플레어 튜브 피팅 매크로'],
   10:['지상 운용과 정비지원','Ground Operations and Servicing','night flight line, ground power unit and marshaller with wands','야간 비행선, 지상전원장치와 유도 신호봉을 든 정비사'],
   11:['규정과 정비 간행물','Regulations and Maintenance Publications','stack of maintenance manuals and an open regulation binder on a hangar desk','격납고 책상 위 정비 교범과 규정집'],
   12:['정비사 권한과 한계','Mechanic Privileges and Limitations','a certified mechanic signing a logbook beside an aircraft','항공기 옆에서 정비 기록부에 서명하는 정비사'],
   13:['정비 기록과 서식','Maintenance Forms and Records','aircraft logbook pages and work order forms with a pen, moody light','정비 기록부와 작업지시서, 은은한 조명'],
   14:['정비 공구','Hand Tools and Measuring Devices','torque wrench, micrometer and safety wire pliers laid out on a shadow board','토크렌치·마이크로미터·안전선 플라이어가 정리된 공구판'],
   15:['항공정비 취업 입문','Starting an Aviation Maintenance Career','young technician walking into a huge hangar at sunrise','해 뜰 무렵 거대한 격납고로 걸어 들어가는 젊은 정비사']}},
 airframe:{ko:'기체',en:'Airframe',site:'airframe',hb:'FAA-H-8083-31B · AMT Handbook — Airframe',acs:'FAA-S-ACS-1 · Aviation Mechanic ACS (Airframe)',
  ch:{1:['항공기 구조','Aircraft Structures','exposed fuselage frames, stringers and bulkheads of a fighter jet in a hangar','격납고 속 전투기 동체의 프레임·스트링거·벌크헤드'],
   2:['공기역학·조립·리깅','Aerodynamics, Assembly and Rigging','control cables and pulleys inside a wing, tensiometer on a cable','날개 속 조종 케이블과 풀리, 케이블 장력계'],
   3:['항공기 우포 외피','Aircraft Fabric Covering','fabric-covered vintage wing ribs being doped under warm light','따뜻한 조명 아래 도프 작업 중인 우포 날개 리브'],
   4:['금속 구조 수리','Sheet Metal Structural Repair','rivet gun and bucking bar on an aluminum skin patch, sparks of light','알루미늄 외피 패치에 리벳건과 버킹바 작업'],
   5:['항공기 용접','Aircraft Welding','TIG welding arc on a steel tube engine mount, blue glow','강관 엔진 마운트에 튀는 파란 TIG 용접 아크'],
   6:['목재 구조 수리','Wood Structures','spruce wing spar and plywood ribs on a workbench, clamps','작업대 위 스프루스 날개 스파와 합판 리브, 클램프'],
   7:['첨단 복합재료','Advanced Composite Materials','carbon fiber weave laid up with vacuum bag on a composite panel','진공백으로 적층 중인 탄소섬유 복합재 패널'],
   8:['도장·마감','Aircraft Painting and Finishing','fighter jet in a paint booth, spray mist in dramatic light','도장 부스 안의 전투기와 극적인 분무 연무'],
   9:['항공기 전기 계통','Aircraft Electrical System','open avionics bay with wire harnesses and circuit breakers','배선 하네스와 회로차단기가 보이는 전자장비실'],
   10:['항공기 계기 계통','Aircraft Instrument Systems','glowing cockpit gauges and glass displays at night','야간에 빛나는 조종석 계기와 디스플레이'],
   11:['통신·항법','Communication and Navigation','antennas on an aircraft spine under a starry sky, radio waves','별빛 아래 기체 상부 안테나와 전파'],
   12:['유압·공압 계통','Hydraulic and Pneumatic Power Systems','hydraulic actuators, pumps and pressure lines inside a wheel well','휠웰 안의 유압 작동기·펌프·압력 라인'],
   13:['착륙장치 계통','Landing Gear Systems','massive main landing gear strut and tire on jacks in a hangar','잭 위에 올려진 거대한 주 착륙장치와 타이어'],
   14:['항공기 연료 계통','Aircraft Fuel System','refueling hose connected to a jet at dusk, fuel tank access panel','해질녘 급유 호스가 연결된 제트기, 연료탱크 점검창'],
   15:['방빙·제우 계통','Ice and Rain Protection','ice forming on a wing leading edge in a winter storm','겨울 폭풍 속 날개 앞전에 착빙되는 모습'],
   16:['객실 환경 제어','Cabin Environmental Control','air cycle machine and ducting behind an open access panel','열린 점검창 뒤의 공기순환장치와 덕트'],
   17:['화재 방지 계통','Fire Protection Systems','red fire extinguisher bottle and detector loop in an engine bay','엔진실 속 붉은 소화기 용기와 화재감지 루프'],
   18:['검사','Inspection','mechanic with a flashlight and mirror inspecting a fighter jet at night','야간에 손전등과 거울로 전투기를 검사하는 정비사']}},
 powerplant:{ko:'동력장치',en:'Powerplant',site:'powerplant',hb:'FAA-H-8083-32B · AMT Handbook — Powerplant',acs:'FAA-S-ACS-1 · Aviation Mechanic ACS (Powerplant)',
  ch:{1:['항공기 엔진 기초','Aircraft Engines','cutaway of a radial piston engine next to a turbofan, dramatic rim light','성형 피스톤 엔진과 터보팬 엔진 단면, 극적인 역광'],
   2:['연료·연료계량 계통','Fuel and Fuel Metering Systems','carburetor and fuel control unit cutaway with glowing fuel paths','연료 흐름이 빛나는 기화기와 연료조절장치 단면'],
   3:['흡입·배기 계통','Induction and Exhaust Systems','engine intake duct and glowing exhaust stacks in the dark','어둠 속 엔진 흡입구와 붉게 달아오른 배기관'],
   4:['점화·전기 계통','Ignition and Electrical Systems','magneto and spark plugs with an electric arc, macro shot','전기 아크가 튀는 마그네토와 점화플러그 매크로'],
   5:['시동 계통','Starting Systems','engine start at night with starter whine, heat shimmer behind the nozzle','야간 엔진 시동, 노즐 뒤 아지랑이'],
   6:['윤활·냉각 계통','Lubrication and Cooling Systems','amber engine oil flowing over gears and an oil cooler','기어 위로 흐르는 호박색 엔진 오일과 오일 쿨러'],
   7:['프로펠러','Propellers','spinning propeller with tip vortices in morning mist','아침 안개 속 회전하는 프로펠러와 끝단 와류'],
   8:['엔진 장·탈착','Engine Removal and Replacement','jet engine being lowered on a hoist onto an engine stand','호이스트로 엔진 스탠드에 내려지는 제트엔진'],
   9:['화재 방지 계통','Engine Fire Protection Systems','engine nacelle with fire detection loop and extinguisher discharge line','화재감지 루프와 소화 배관이 있는 엔진 나셀'],
   10:['정비·작동·검사','Engine Maintenance and Operation','borescope image inside a turbine, technician watching the screen','보어스코프 화면으로 터빈 내부를 보는 정비사'],
   11:['경량스포츠기 엔진','Light-Sport Aircraft Engines','compact light-sport aircraft engine on a test stand, clean workshop','깔끔한 작업장 시험대 위 소형 경량항공기 엔진'],
   12:['가스터빈 엔진','Gas Turbine Engines','turbofan engine cutaway, compressor blades and combustor glowing orange','압축기 블레이드와 주황빛 연소실이 보이는 터보팬 단면']}}
};
var HASH={ko:'#항공정비 #MRO #항공정비사 #AeroMechExpert #항공산업',en:'#AviationMaintenance #MRO #AeroMechExpert #KoreaMRO #AircraftTechnician'};
var SITE_URL='https://inbeabang-wq.github.io/';
